import {
  DevsDungeon,
  EClubIIITBhagalpur,
  GCEArwal,
  GDSCBCEPatna,
  GDSCSCE,
  GDSC_GCE,
  GDSC_GEC_Sheikhpura,
  GDSC_IIBMPatna,
  GDSC_IITP,
  GDSC_NCE,
  GDSC_SEC_Sasaram,
  HackBeats,
  MetaHorizon,
  NITP,
} from "../../assets/CommunityPartners";

export const CommunityPartnersList = [
  {
    name: "GDSC IIT Patna",
    logo: GDSC_IITP,
    url: "https://gdsc.community.dev/indian-institute-of-technology-patna/",
    linkedin: "https://www.linkedin.com/company/dsciitp/",
    twitter: "https://twitter.com/dsciitpatna/",
  },
  {
    name: "GDSC GCE",
    logo: GDSC_GCE,
    url: "https://gdsc.community.dev/gaya-college-of-engineering-gaya/",
    linkedin: "https://www.linkedin.com/company/74913008/member/",
    twitter: "https://twitter.com/dsc_gce/",
  },
  {
    name: "GDSC SCE Saharsa",
    logo: GDSCSCE,
    url: "https://gdsc.community.dev/saharsa-college-of-engineering-saharsa/",
    linkedin: "https://www.linkedin.com/company/74913008/member/",
    twitter: "https://twitter.com/GdscSaharsa",
  },
  {
    name: "GDSC IIBM Patna",
    logo: GDSC_IIBMPatna,
    url: "https://gdsc.community.dev/indian-institute-of-business-management-patna/",
    linkedin:
      "https://www.linkedin.com/company/google-developer-student-clubs-iibm-patna/",
    instagram: "https://instagram.com/gdsciibmpatna",
  },
  {
    name: "GDSC NCE",
    logo: GDSC_NCE,
    linkedin: "http://www.linkedin.com/vanisha-samriddhi",
  },
  {
    name: "Meta Horizon",
    logo: MetaHorizon,
    linkedin: "https://www.linkedin.com/company/meta-horizon/",
    twitter: "https://twitter.com/metahorizon_",
  },
  {
    name: "Devs Dungeon",
    logo: DevsDungeon,
    url: "http://bit.ly/devs-dungeon-bio",
    linkedin: "https://www.linkedin.com/company/devs-dungeon/",
    instagram: "https://www.instagram.com/devs.dungeon/",
    twitter: "https://twitter.com/devs_dungeon",
  },
  {
    name: "Hack Beats",
    logo: HackBeats,
    url: "https://hackbeatsorg.bio.link/",
    linkedin: "https://www.linkedin.com/company/hackbeats/",
    instagram: "https://instagram.com/hack_beats_offical/",
    twitter: "https://twitter.com/hackbeatsorg/",
  },
  {
    name: "GDSC BCE Patna",
    logo: GDSCBCEPatna,
    url: "https://gdsc.community.dev/bakhtiyarpur-college-of-engineering-patna/",
    linkedin: "https://www.linkedin.com/company/gdsc-bce-patna/",
    instagram: "https://www.instagram.com/gdscbcepatna/",
    youtube: "https://www.youtube.com/@gdscbcepatna",
  },
  {
    name: "Entrepreneurship Club IIITBH",
    logo: EClubIIITBhagalpur,
    linkedin: "https://www.linkedin.com/in/jayam-pandit-6293aa216/",
  },
  {
    name: "GEC Arwal Community",
    logo: GCEArwal,
    url: "http://gecarwal.ac.in",
    instagram: "https://instagram.com/gecarwal22",
    twitter: "https://twitter.com/Gecarwal22",
  },
  {
    name: "GDSC GEC Sheikhpura",
    logo: GDSC_GEC_Sheikhpura,
    url: "https://gdsc.community.dev/government-engineering-college-sheikhpura/",
    instagram: "https://www.instagram.com/gdsc.gecsheikhpura/",
    youTube: "https://youtube.com/@gdscgecsheikhpura6743",
    linkedin: "https://www.linkedin.com/company/gdsc-gec-sheikhpura/",
  },
  {
    name: "GDSC SEC Sasaram",
    logo: GDSC_SEC_Sasaram,
    url: "https://gdsc.community.dev/sershah-engineering-college-sasaram/",
    linkedin: "https://www.linkedin.com/company/gdsc-sec-sasaram/",
    instagram: "https://www.instagram.com/gdsc.sec.sasaram/",
  },
  {
    name: "GDSC NITP",
    logo: NITP,
    url: "https://gdsc.community.dev/national-institute-of-technology-nit-patna/",
  },
];
